org: galer7
app: aws-node-project
service: aws-node-project

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  stage: development
  region: us-east-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - ses:SendEmail
            - ses:SendRawEmail
          Resource: '*'

stepFunctions:
  stateMachines:
    reminderMachine:
      definition:
        StartAt: Delay
        States:
          Delay:
            Type: Wait
            TimestampPath: "$.expirydate"
            Next: TriggerLambda
          TriggerLambda:
            Type: Task
            Resource:
              Fn::GetAtt: [sendReminder, Arn]
            End: true
      events:
        - http:
            path: /set-reminder
            method: post

functions:
  sendReminder:
    handler: aws/handler.sendReminder
    events:
      - http:
          path: /send-reminder
          method: post

plugins:
  - serverless-bundle
  - serverless-step-functions

custom:
  serverlessPluginTypescript:
    tsConfigFileLocation: './aws/tsconfig.json'